name: Deploy Lambda and Terraform

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: Deploy Lambda + Terraform
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      LAMBDA_FUNCTION_NAME: task-tracker-api

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Terraform Init
      run: terraform init
      working-directory: infra

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: infra

    - name: Zip Lambda function
      run: |
        cd lambda
        zip -r ../infra/function.zip .
        cd ../infra

    - name: Upload Lambd

